version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule: { interval: weekly }
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types: [minor, patch]
  - package-ecosystem: npm
    directory: /infra
    schedule: { interval: weekly }
    open-pull-requests-limit: 3
    groups:
      cdk:
        patterns: ["aws-cdk*", "constructs"]
  - package-ecosystem: npm
    directory: /e2e
    schedule: { interval: monthly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /
    schedule: { interval: weekly }
