import { drizzle } from "drizzle-orm/postgres-js";
import { migrateWithLock } from "@pointup/core";
import postgres from "postgres";

/**
 * Applies pending SQL migrations (generated by drizzle-kit into
 * packages/core/drizzle, baked into the worker image). Runs as a one-off
 * task after each deploy, before traffic hits new code paths.
 */
export async function runMigrations(databaseUrl: string): Promise<void> {
  const migrationsFolder = process.env.MIGRATIONS_DIR ?? "./drizzle";
  console.info(`[migrate] applying migrations from ${migrationsFolder}`);

  // One reserved connection holds the explicit session lock while Drizzle
  // uses the other connection for its journal reads and migration transaction.
  const client = postgres(databaseUrl, { max: 2 });
  try {
    await migrateWithLock(drizzle(client), { migrationsFolder });
    console.info("[migrate] done");
  } finally {
    await client.end();
  }
}
