import { runLockedMigrations } from "@pointup/core";

/**
 * Applies pending SQL migrations (generated by drizzle-kit into
 * packages/core/drizzle, baked into the worker image). Runs as a one-off
 * task after each deploy, before traffic hits new code paths.
 */
export async function runMigrations(databaseUrl: string): Promise<void> {
  const migrationsFolder = process.env.MIGRATIONS_DIR ?? "./drizzle";
  console.info(`[migrate] applying migrations from ${migrationsFolder}`);

  await runLockedMigrations(databaseUrl, { migrationsFolder });
  console.info("[migrate] done");
}
