import { runLockedMigrations } from "@pointup/core";

/**
 * Applies pending SQL migrations (generated by drizzle-kit into
 * packages/core/drizzle, baked into the worker image). Runs as a one-off
 * candidate task before new application hosts and schedules activate.
 */
export async function runMigrations(databaseUrl: string): Promise<void> {
  const migrationsFolder = process.env.MIGRATIONS_DIR ?? "./drizzle";
  console.info("[migrate] applying managed migrations");

  try {
    await runLockedMigrations(databaseUrl, { migrationsFolder }, {
      expectedManifestSha256: process.env.EXPECTED_MIGRATION_MANIFEST_SHA256,
      verifyApplicationSchema: true,
      onAttested: attestation => new Promise<void>((resolve, reject) => {
        // Flush the safe attestation before the worker can exit. This is stdout
        // evidence, not a claim that the deployment's log transport delivered it.
        process.stdout.write(JSON.stringify(attestation) + "\n", error => {
          if (error) reject(new Error("Migration attestation output failed."));
          else resolve();
        });
      }),
    });
  } catch {
    // Driver exceptions may carry private connection details or SQL parameters.
    throw new Error("Managed migration task failed; verify candidate manifest and database journal.");
  }
  console.info("[migrate] done");
}
