import type { ProviderDefinition } from "./types";

export const AIRLINE_PROVIDERS: readonly ProviderDefinition[] = [
  {
    id: "united",
    kind: "airline",
    displayName: "United Airlines",
    pointsCurrency: "MileagePlus miles",
    estimatedCentsPerPoint: 1.2,
    inactivityExpiryMonths: 18,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://www.united.com/en/us/myunited",
      allowedHosts: ["united.com"],
      hint: "MileagePlus miles shown in the account header or summary card",
    },
  },
  {
    id: "delta",
    kind: "airline",
    displayName: "Delta Air Lines",
    pointsCurrency: "SkyMiles",
    estimatedCentsPerPoint: 1.1,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://www.delta.com/myprofile/overview",
      allowedHosts: ["delta.com"],
      hint: "SkyMiles balance on the profile overview",
    },
  },
  {
    id: "american",
    kind: "airline",
    displayName: "American Airlines",
    pointsCurrency: "AAdvantage miles",
    estimatedCentsPerPoint: 1.4,
    inactivityExpiryMonths: 24,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://www.aa.com/aadvantage-program/profile/account-summary",
      allowedHosts: ["aa.com"],
      hint: "AAdvantage miles on the account summary",
    },
  },
  {
    id: "alaska-atmos-rewards",
    kind: "airline",
    displayName: "Alaska Airlines / Hawaiian Airlines (Atmos Rewards)",
    pointsCurrency: "Atmos Rewards points",
    estimatedCentsPerPoint: 1.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Mileage Plan", "Alaska Mileage Plan", "HawaiianMiles", "Hawaiian Airlines", "Atmos"],
    region: "US",
    alliance: "oneworld",
    agentSkill: {
      startUrl: "https://www.alaskaair.com/account/overview",
      allowedHosts: ["alaskaair.com"],
      hint: "Atmos Rewards points balance on the account overview",
      notes: ["Mileage Plan and HawaiianMiles were folded into Atmos Rewards; verify legacy balance display."],
    },
  },
  {
    id: "jetblue-trueblue",
    kind: "airline",
    displayName: "JetBlue",
    pointsCurrency: "TrueBlue points",
    estimatedCentsPerPoint: 1.3,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["TrueBlue", "JetBlue TrueBlue"],
    region: "US",
    agentSkill: {
      startUrl: "https://www.jetblue.com/trueblue",
      allowedHosts: ["jetblue.com"],
      hint: "TrueBlue points balance in the account header",
    },
  },
  {
    id: "southwest-rapid-rewards",
    kind: "airline",
    displayName: "Southwest Airlines",
    pointsCurrency: "Rapid Rewards points",
    estimatedCentsPerPoint: 1.4,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Rapid Rewards", "Southwest"],
    region: "US",
    agentSkill: {
      startUrl: "https://www.southwest.com/myaccount/",
      allowedHosts: ["southwest.com"],
      hint: "Rapid Rewards points balance on the My Account page",
    },
  },
  {
    id: "spirit-free-spirit",
    kind: "airline",
    displayName: "Spirit Airlines",
    pointsCurrency: "Free Spirit points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 12,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Free Spirit", "Spirit"],
    region: "US",
  },
  {
    id: "frontier-miles",
    kind: "airline",
    displayName: "Frontier Airlines",
    pointsCurrency: "Frontier Miles",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 6,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Frontier Miles", "Frontier"],
    region: "US",
  },
  {
    id: "allegiant-rewards",
    kind: "airline",
    displayName: "Allegiant Air",
    pointsCurrency: "Allegiant Rewards points",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Allegiant"],
    region: "US",
  },
  {
    id: "air-canada-aeroplan",
    kind: "airline",
    displayName: "Air Canada",
    pointsCurrency: "Aeroplan points",
    estimatedCentsPerPoint: 1.5,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Aeroplan"],
    region: "CA",
    alliance: "star_alliance",
    agentSkill: {
      startUrl: "https://www.aircanada.com/aeroplan/member/dashboard",
      allowedHosts: ["aircanada.com"],
      hint: "Aeroplan points balance on the member dashboard",
    },
  },
  {
    id: "westjet-rewards",
    kind: "airline",
    displayName: "WestJet",
    pointsCurrency: "WestJet dollars",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["WestJet Rewards", "WestJet dollars"],
    region: "CA",
    agentSkill: {
      startUrl: "https://www.westjet.com/en-ca/rewards",
      allowedHosts: ["westjet.com"],
      hint: "WestJet dollars balance (1 WSD = 1 CAD, value shown in dollars not points)",
      notes: ["Currency is WestJet dollars (CAD-denominated); points-to-USD estimate applies the CAD/USD rate roughly."],
    },
  },
  {
    id: "british-airways-avios",
    kind: "airline",
    displayName: "British Airways Executive Club",
    pointsCurrency: "Avios",
    estimatedCentsPerPoint: 1.3,
    inactivityExpiryMonths: 36,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Executive Club", "BA Avios", "Avios"],
    region: "GB",
    alliance: "oneworld",
    agentSkill: {
      startUrl: "https://www.britishairways.com/travel/viewaccount/execclub/_gf/en_gb",
      allowedHosts: ["britishairways.com", "ba.com"],
      hint: "Avios balance in the Executive Club account header",
    },
  },
  {
    id: "iberia-plus",
    kind: "airline",
    displayName: "Iberia Plus",
    pointsCurrency: "Iberia Avios",
    estimatedCentsPerPoint: 1.3,
    inactivityExpiryMonths: 36,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Iberia Avios", "Iberia"],
    region: "ES",
    alliance: "oneworld",
    agentSkill: {
      startUrl: "https://www.iberia.com/us/iberiaplus/",
      allowedHosts: ["iberia.com"],
      hint: "Avios balance in the Iberia Plus area",
    },
  },
  {
    id: "aer-lingus-aerclub",
    kind: "airline",
    displayName: "Aer Lingus AerClub",
    pointsCurrency: "Avios",
    estimatedCentsPerPoint: 1.3,
    inactivityExpiryMonths: 36,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["AerClub", "Aer Lingus"],
    region: "IE",
    agentSkill: {
      startUrl: "https://www.aerlingus.com/html/aerclub/",
      allowedHosts: ["aerlingus.com"],
      hint: "Avios balance in the AerClub account",
    },
  },
  {
    id: "virgin-atlantic-flying-club",
    kind: "airline",
    displayName: "Virgin Atlantic Flying Club",
    pointsCurrency: "Flying Club points",
    estimatedCentsPerPoint: 1.4,
    inactivityExpiryMonths: 36,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Flying Club", "Virgin Atlantic"],
    region: "GB",
    alliance: "skyteam",
    agentSkill: {
      startUrl: "https://www.virginatlantic.com/flying-club/",
      allowedHosts: ["virginatlantic.com"],
      hint: "Flying Club points balance in the member header",
    },
  },
  {
    id: "flying-blue",
    kind: "airline",
    displayName: "Air France-KLM Flying Blue",
    pointsCurrency: "Flying Blue miles",
    estimatedCentsPerPoint: 1.2,
    inactivityExpiryMonths: 24,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Flying Blue", "Air France", "KLM"],
    region: "FR",
    alliance: "skyteam",
    agentSkill: {
      startUrl: "https://www.flyingblue.com/en/",
      allowedHosts: ["flyingblue.com", "airfrance.com", "klm.com"],
      hint: "Flying Blue miles balance in the account header",
    },
  },
  {
    id: "miles-and-more",
    kind: "airline",
    displayName: "Lufthansa Group Miles & More",
    pointsCurrency: "Miles & More miles",
    estimatedCentsPerPoint: 1.2,
    inactivityExpiryMonths: 36,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Miles & More", "Lufthansa", "Swiss", "Austrian", "Brussels Airlines", "Eurowings"],
    region: "DE",
    alliance: "star_alliance",
    agentSkill: {
      startUrl: "https://www.miles-and-more.com/row/en.html",
      allowedHosts: ["miles-and-more.com"],
      hint: "Award miles balance in the member header",
      notes: ["One program for Lufthansa, SWISS, Austrian, Brussels, Eurowings; expiry rules vary by status, verify."],
    },
  },
  {
    id: "sas-eurobonus",
    kind: "airline",
    displayName: "SAS EuroBonus",
    pointsCurrency: "EuroBonus points",
    estimatedCentsPerPoint: 1.1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["EuroBonus", "SAS"],
    region: "SE",
    agentSkill: {
      startUrl: "https://www.flysas.com/en/eurobonus/",
      allowedHosts: ["flysas.com"],
      hint: "EuroBonus points balance in the member header",
    },
  },
  {
    id: "finnair-plus",
    kind: "airline",
    displayName: "Finnair Plus",
    pointsCurrency: "Avios",
    estimatedCentsPerPoint: 1.3,
    inactivityExpiryMonths: 36,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Finnair Plus", "Finnair Avios"],
    region: "FI",
    alliance: "oneworld",
    agentSkill: {
      startUrl: "https://www.finnair.com/en/finnair-plus",
      allowedHosts: ["finnair.com"],
      hint: "Avios balance in the Finnair Plus account",
    },
  },
  {
    id: "tap-miles-and-go",
    kind: "airline",
    displayName: "TAP Air Portugal Miles&Go",
    pointsCurrency: "Miles&Go miles",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 36,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Miles&Go", "TAP"],
    region: "PT",
    alliance: "star_alliance",
  },
  {
    id: "turkish-miles-and-smiles",
    kind: "airline",
    displayName: "Turkish Airlines Miles&Smiles",
    pointsCurrency: "Miles",
    estimatedCentsPerPoint: 1.3,
    inactivityExpiryMonths: 36,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Miles&Smiles", "Turkish"],
    region: "TR",
    alliance: "star_alliance",
    agentSkill: {
      startUrl: "https://www.turkishairlines.com/en-us/miles-and-smiles/",
      allowedHosts: ["turkishairlines.com"],
      hint: "Miles balance in the Miles&Smiles account",
    },
  },
  {
    id: "lot-miles-and-more",
    kind: "airline",
    displayName: "LOT Polish Airlines Miles & More",
    pointsCurrency: "Miles & More miles",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 36,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["LOT", "LOT Polish"],
    region: "PL",
    alliance: "star_alliance",
  },
  {
    id: "ita-airways-volare",
    kind: "airline",
    displayName: "ITA Airways Volare",
    pointsCurrency: "Volare miles",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Volare", "ITA Airways"],
    region: "IT",
  },
  {
    id: "norse-atlantic-airways",
    kind: "airline",
    displayName: "Norse Atlantic Airways",
    pointsCurrency: "Norse Points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Norse", "Norse Atlantic"],
    region: "NO",
  },
  {
    id: "emirates-skywards",
    kind: "airline",
    displayName: "Emirates Skywards",
    pointsCurrency: "Skywards Miles",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 36,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Skywards", "Emirates"],
    region: "AE",
    agentSkill: {
      startUrl: "https://www.emirates.com/account/english/light-registration/",
      allowedHosts: ["emirates.com"],
      hint: "Skywards Miles balance in the account header",
    },
  },
  {
    id: "etihad-guest",
    kind: "airline",
    displayName: "Etihad Guest",
    pointsCurrency: "Etihad Guest Miles",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 36,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Etihad", "Etihad Guest Miles"],
    region: "AE",
    agentSkill: {
      startUrl: "https://www.etihad.com/en/etihadguest",
      allowedHosts: ["etihad.com"],
      hint: "Etihad Guest Miles balance in the member header",
    },
  },
  {
    id: "qatar-privilege-club",
    kind: "airline",
    displayName: "Qatar Airways Privilege Club",
    pointsCurrency: "Avios",
    estimatedCentsPerPoint: 1.3,
    inactivityExpiryMonths: 36,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Privilege Club", "Qatar Avios", "Qatar Airways"],
    region: "QA",
    alliance: "oneworld",
    agentSkill: {
      startUrl: "https://www.qatarairways.com/en/privilege-club.html",
      allowedHosts: ["qatarairways.com"],
      hint: "Avios balance in the Privilege Club account",
    },
  },
  {
    id: "saudia-alfursan",
    kind: "airline",
    displayName: "Saudia Alfursan",
    pointsCurrency: "Alfursan miles",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Alfursan", "Saudia"],
    region: "SA",
    alliance: "skyteam",
  },
  {
    id: "egyptair-plus",
    kind: "airline",
    displayName: "EgyptAir Plus",
    pointsCurrency: "EgyptAir Plus miles",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["EgyptAir"],
    region: "EG",
    alliance: "star_alliance",
  },
  {
    id: "ethiopian-shebamiles",
    kind: "airline",
    displayName: "Ethiopian Airlines ShebaMiles",
    pointsCurrency: "ShebaMiles",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["ShebaMiles", "Ethiopian"],
    region: "ET",
    alliance: "star_alliance",
  },
  {
    id: "kenya-airways-flying-blue",
    kind: "airline",
    displayName: "Kenya Airways (Flying Blue)",
    pointsCurrency: "Flying Blue miles",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 24,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Kenya Airways", "Asante Rewards"],
    region: "KE",
    alliance: "skyteam",
  },
  {
    id: "rwandair-rwandair-plus",
    kind: "airline",
    displayName: "RwandAir Cheza",
    pointsCurrency: "RwandAir miles",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["RwandAir", "Cheza"],
    region: "RW",
  },
  {
    id: "singapore-krisflyer",
    kind: "airline",
    displayName: "Singapore Airlines KrisFlyer",
    pointsCurrency: "KrisFlyer miles",
    estimatedCentsPerPoint: 1.5,
    inactivityExpiryMonths: 36,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["KrisFlyer", "Singapore Airlines"],
    region: "SG",
    alliance: "star_alliance",
    agentSkill: {
      startUrl: "https://www.singaporeair.com/en_UK/ppsclub-krisflyer/",
      allowedHosts: ["singaporeair.com"],
      hint: "KrisFlyer miles balance in the member header",
    },
  },
  {
    id: "cathay-asia-miles",
    kind: "airline",
    displayName: "Cathay Pacific Asia Miles",
    pointsCurrency: "Asia Miles",
    estimatedCentsPerPoint: 1.2,
    inactivityExpiryMonths: 36,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Asia Miles", "Cathay Pacific", "Cathay"],
    region: "HK",
    alliance: "oneworld",
    agentSkill: {
      startUrl: "https://www.cathaypacific.com/cx/en_US/membership.html",
      allowedHosts: ["cathaypacific.com"],
      hint: "Asia Miles balance in the member header",
    },
  },
  {
    id: "ana-mileage-club",
    kind: "airline",
    displayName: "ANA Mileage Club",
    pointsCurrency: "ANA miles",
    estimatedCentsPerPoint: 1.5,
    inactivityExpiryMonths: 36,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["ANA", "All Nippon Airways"],
    region: "JP",
    alliance: "star_alliance",
    agentSkill: {
      startUrl: "https://www.ana.co.jp/en/us/amc/",
      allowedHosts: ["ana.co.jp"],
      hint: "ANA mileage balance in the AMC member area",
    },
  },
  {
    id: "jal-mileage-bank",
    kind: "airline",
    displayName: "JAL Mileage Bank",
    pointsCurrency: "JAL miles",
    estimatedCentsPerPoint: 1.4,
    inactivityExpiryMonths: 36,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["JMB", "JAL", "Japan Airlines"],
    region: "JP",
    alliance: "oneworld",
    agentSkill: {
      startUrl: "https://www.jal.co.jp/en/jmb/",
      allowedHosts: ["jal.co.jp"],
      hint: "Mileage balance in the JMB member area",
    },
  },
  {
    id: "korean-air-skypass",
    kind: "airline",
    displayName: "Korean Air SKYPASS",
    pointsCurrency: "SKYPASS miles",
    estimatedCentsPerPoint: 1.5,
    inactivityExpiryMonths: 120,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["SKYPASS", "Korean Air"],
    region: "KR",
    alliance: "skyteam",
    agentSkill: {
      startUrl: "https://www.koreanair.com/skypass",
      allowedHosts: ["koreanair.com"],
      hint: "SKYPASS miles balance in the account header",
    },
  },
  {
    id: "asiana-club",
    kind: "airline",
    displayName: "Asiana Club",
    pointsCurrency: "Asiana miles",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Asiana"],
    region: "KR",
  },
  {
    id: "thai-royal-orchid-plus",
    kind: "airline",
    displayName: "Thai Airways Royal Orchid Plus",
    pointsCurrency: "Royal Orchid Plus miles",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 36,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Royal Orchid Plus", "Thai Airways", "ROP"],
    region: "TH",
    alliance: "star_alliance",
  },
  {
    id: "malaysia-enrich",
    kind: "airline",
    displayName: "Malaysia Airlines Enrich",
    pointsCurrency: "Enrich points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 36,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Enrich", "Malaysia Airlines"],
    region: "MY",
    alliance: "oneworld",
  },
  {
    id: "garuda-indonesia-garudamiles",
    kind: "airline",
    displayName: "Garuda Indonesia GarudaMiles",
    pointsCurrency: "GarudaMiles",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["GarudaMiles", "Garuda"],
    region: "ID",
    alliance: "skyteam",
  },
  {
    id: "philippine-airlines-mabuhay-miles",
    kind: "airline",
    displayName: "Philippine Airlines Mabuhay Miles",
    pointsCurrency: "Mabuhay Miles",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Mabuhay Miles", "PAL"],
    region: "PH",
  },
  {
    id: "vietnam-airlines-lotusmiles",
    kind: "airline",
    displayName: "Vietnam Airlines Lotusmiles",
    pointsCurrency: "Lotusmiles",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Lotusmiles", "Vietnam Airlines"],
    region: "VN",
    alliance: "skyteam",
  },
  {
    id: "eva-air-infinity-mileagelands",
    kind: "airline",
    displayName: "EVA Air Infinity MileageLands",
    pointsCurrency: "Infinity MileageLands miles",
    estimatedCentsPerPoint: 1.2,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Infinity MileageLands", "EVA Air", "EVA"],
    region: "TW",
    alliance: "star_alliance",
  },
  {
    id: "china-airlines-dynasty-flyer",
    kind: "airline",
    displayName: "China Airlines Dynasty Flyer",
    pointsCurrency: "Dynasty Flyer miles",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Dynasty Flyer", "China Airlines"],
    region: "TW",
    alliance: "skyteam",
  },
  {
    id: "air-china-phoenixmiles",
    kind: "airline",
    displayName: "Air China PhoenixMiles",
    pointsCurrency: "PhoenixMiles",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["PhoenixMiles", "Air China"],
    region: "CN",
    alliance: "star_alliance",
  },
  {
    id: "china-eastern-eastern-miles",
    kind: "airline",
    displayName: "China Eastern Eastern Miles",
    pointsCurrency: "Eastern Miles",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Eastern Miles", "China Eastern"],
    region: "CN",
    alliance: "skyteam",
  },
  {
    id: "china-southern-sky-pearl-club",
    kind: "airline",
    displayName: "China Southern Sky Pearl Club",
    pointsCurrency: "Sky Pearl miles",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Sky Pearl Club", "China Southern"],
    region: "CN",
    alliance: "skyteam",
  },
  {
    id: "air-india-maharaja-club",
    kind: "airline",
    displayName: "Air India Maharaja Club",
    pointsCurrency: "Flying Returns points",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Maharaja Club", "Flying Returns", "Air India"],
    region: "IN",
    alliance: "star_alliance",
  },
  {
    id: "indigo-6e-rewards",
    kind: "airline",
    displayName: "IndiGo BluChip",
    pointsCurrency: "BluChip points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["BluChip", "6E Rewards", "IndiGo"],
    region: "IN",
    agentSkill: {
      startUrl: "https://www.goindigo.in/",
      allowedHosts: ["goindigo.in"],
      hint: "BluChip balance in the logged-in account header",
      notes: ["BluChip is revenue-based (1 BluChip ~ INR 1)."],
    },
  },
  {
    id: "qantas-frequent-flyer",
    kind: "airline",
    displayName: "Qantas Frequent Flyer",
    pointsCurrency: "Qantas Points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 18,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Qantas", "QFF", "Qantas Points"],
    region: "AU",
    alliance: "oneworld",
    agentSkill: {
      startUrl: "https://www.qantas.com/au/en/frequent-flyer.html",
      allowedHosts: ["qantas.com"],
      hint: "Qantas Points balance in the member header",
    },
  },
  {
    id: "virgin-australia-velocity",
    kind: "airline",
    displayName: "Virgin Australia Velocity",
    pointsCurrency: "Velocity Points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Velocity", "Virgin Australia"],
    region: "AU",
    agentSkill: {
      startUrl: "https://www.virginaustralia.com/au/en/velocity/",
      allowedHosts: ["virginaustralia.com"],
      hint: "Velocity Points balance in the member header",
    },
  },
  {
    id: "air-new-zealand-airpoints",
    kind: "airline",
    displayName: "Air New Zealand Airpoints",
    pointsCurrency: "Airpoints Dollars",
    estimatedCentsPerPoint: 60,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Airpoints", "Air New Zealand"],
    region: "NZ",
    alliance: "star_alliance",
    agentSkill: {
      startUrl: "https://www.airnewzealand.com/airpoints",
      allowedHosts: ["airnewzealand.com"],
      hint: "Airpoints Dollars balance in the member area",
      notes: ["Currency is Airpoints Dollars (NZD-denominated, 1 AD ~ 1 NZD), not miles; shown as dollars. Estimate ~60 USc/AD is an approximate NZD->USD conversion."],
    },
  },
  {
    id: "latam-pass",
    kind: "airline",
    displayName: "LATAM Pass",
    pointsCurrency: "LATAM Pass points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 24,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["LATAM", "LATAM Pass"],
    region: "CL",
    agentSkill: {
      startUrl: "https://www.latamairlines.com/us/en/latam-pass",
      allowedHosts: ["latamairlines.com"],
      hint: "LATAM Pass points balance in the member header",
    },
  },
  {
    id: "avianca-lifemiles",
    kind: "airline",
    displayName: "Avianca LifeMiles",
    pointsCurrency: "LifeMiles",
    estimatedCentsPerPoint: 1.5,
    inactivityExpiryMonths: 12,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["LifeMiles", "Avianca"],
    region: "CO",
    alliance: "star_alliance",
    agentSkill: {
      startUrl: "https://www.lifemiles.com/",
      allowedHosts: ["lifemiles.com"],
      hint: "LifeMiles balance in the member header",
    },
  },
  {
    id: "copa-connectmiles",
    kind: "airline",
    displayName: "Copa Airlines ConnectMiles",
    pointsCurrency: "ConnectMiles",
    estimatedCentsPerPoint: 1.2,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["ConnectMiles", "Copa"],
    region: "PA",
    alliance: "star_alliance",
    agentSkill: {
      startUrl: "https://www.copaair.com/en-us/connectmiles/",
      allowedHosts: ["copaair.com"],
      hint: "ConnectMiles balance in the member header",
    },
  },
  {
    id: "aeromexico-club-premier",
    kind: "airline",
    displayName: "Aeromexico Club Premier",
    pointsCurrency: "Club Premier points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Club Premier", "Aeromexico"],
    region: "MX",
    alliance: "skyteam",
    agentSkill: {
      startUrl: "https://www.clubpremier.com/",
      allowedHosts: ["clubpremier.com", "aeromexico.com"],
      hint: "Club Premier points balance in the member header",
    },
  },
  {
    id: "azul-fidelidade",
    kind: "airline",
    displayName: "Azul Fidelidade",
    pointsCurrency: "Azul points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Azul", "TudoAzul"],
    region: "BR",
  },
  {
    id: "gol-smiles",
    kind: "airline",
    displayName: "GOL Smiles",
    pointsCurrency: "Smiles miles",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Smiles", "GOL"],
    region: "BR",
  },
];
