import type { AgentSkillSeed, ProviderDefinitionShape } from "./types";

const REVIEWED = "2026-10-01";
const PRIVACY_NOTE =
  "Rewards pages are authenticated: read only the points total; never read or record card numbers, statements or any other account balance.";

/** Bank rewards balance seed rooted at the issuer's own site. */
function bankSeed(
  startUrl: string,
  allowedHosts: readonly string[],
  hint: string,
): AgentSkillSeed {
  return { startUrl, allowedHosts, hint, notes: [PRIVACY_NOTE] };
}

export const CARD_PROVIDERS = [
  {
    id: "chase-ultimate-rewards",
    kind: "credit_card",
    displayName: "Chase Ultimate Rewards",
    pointsCurrency: "Ultimate Rewards points",
    estimatedCentsPerPoint: 1.6,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://ultimaterewardspoints.chase.com/",
      allowedHosts: ["chase.com"],
      hint: "Ultimate Rewards points total (not a single card's cash back)",
    },
  },
  {
    id: "amex-membership-rewards",
    kind: "credit_card",
    displayName: "Amex Membership Rewards",
    pointsCurrency: "Membership Rewards points",
    estimatedCentsPerPoint: 1.6,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://global.americanexpress.com/rewards",
      allowedHosts: ["americanexpress.com"],
      hint: "Membership Rewards points total",
    },
  },
  {
    id: "capital-one-miles",
    kind: "credit_card",
    displayName: "Capital One Rewards",
    pointsCurrency: "Capital One miles",
    estimatedCentsPerPoint: 1.5,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://myrewards.capitalone.com/",
      allowedHosts: ["capitalone.com"],
      hint: "Capital One miles balance",
    },
  },
  {
    id: "citi-thankyou",
    kind: "credit_card",
    displayName: "Citi ThankYou Rewards",
    pointsCurrency: "ThankYou Points",
    estimatedCentsPerPoint: 1.5,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://www.thankyou.com/",
      allowedHosts: ["thankyou.com","citi.com"],
      hint: "ThankYou points balance",
    },
  },
  {
    id: "bilt",
    kind: "credit_card",
    displayName: "Bilt Rewards",
    pointsCurrency: "Bilt Points",
    estimatedCentsPerPoint: 1.8,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://www.bilt.com/rewards",
      allowedHosts: ["bilt.com","biltrewards.com"],
      hint: "Bilt Rewards points balance",
    },
  },
  {
    id: "wells-fargo-rewards",
    kind: "credit_card",
    displayName: "Wells Fargo Rewards",
    pointsCurrency: "Wells Fargo Rewards points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: REVIEWED,
    region: "US",
    aliases: ["Autograph points", "Active Cash"],
    agentSkill: bankSeed("https://www.wellsfargo.com/", ["wellsfargo.com"], "Wells Fargo Rewards points total"),
  },
  {
    id: "bank-of-america-preferred-rewards",
    kind: "credit_card",
    displayName: "Bank of America Rewards",
    pointsCurrency: "Bank of America Points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: REVIEWED,
    region: "US",
    aliases: ["BofA points", "Preferred Rewards"],
    agentSkill: bankSeed("https://www.bankofamerica.com/", ["bankofamerica.com"], "Bank of America Rewards points total"),
  },
  {
    id: "us-bank-altitude",
    kind: "credit_card",
    displayName: "U.S. Bank Altitude Rewards",
    pointsCurrency: "Altitude Rewards points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "US",
    aliases: ["Altitude Connect", "Altitude Go", "Altitude Reserve"],
    agentSkill: bankSeed("https://www.usbank.com/", ["usbank.com"], "U.S. Bank Altitude points total"),
  },
  {
    id: "discover-cashback",
    kind: "credit_card",
    displayName: "Discover Cashback Bonus",
    pointsCurrency: "Discover Cashback Bonus",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "high",
    lastReviewed: REVIEWED,
    region: "US",
    aliases: ["Discover cash back"],
    agentSkill: bankSeed("https://www.discover.com/", ["discover.com"], "Cashback Bonus dollar balance (1 dollar = 100 points)"),
  },
  {
    id: "apple-card-daily-cash",
    kind: "credit_card",
    displayName: "Apple Card Daily Cash",
    pointsCurrency: "Daily Cash",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "high",
    lastReviewed: REVIEWED,
    region: "US",
    aliases: ["Apple Cash", "Daily Cash"],
  },
  {
    id: "pnc-points",
    kind: "credit_card",
    displayName: "PNC Points",
    pointsCurrency: "PNC Points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "US",
    agentSkill: bankSeed("https://www.pnc.com/", ["pnc.com"], "PNC Points total"),
  },
  {
    id: "truist-rewards",
    kind: "credit_card",
    displayName: "Truist Rewards",
    pointsCurrency: "Truist Rewards points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "US",
    agentSkill: bankSeed("https://www.truist.com/", ["truist.com"], "Truist Rewards points total"),
  },
  {
    id: "navy-federal-flagship-rewards",
    kind: "credit_card",
    displayName: "Navy Federal Rewards",
    pointsCurrency: "Navy Federal rewards points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "US",
    aliases: ["Flagship Rewards"],
    agentSkill: bankSeed("https://www.navyfederal.org/", ["navyfederal.org"], "Rewards points total"),
  },
  {
    id: "usaa-rewards",
    kind: "credit_card",
    displayName: "USAA Rewards",
    pointsCurrency: "USAA Rewards points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "US",
    agentSkill: bankSeed("https://www.usaa.com/", ["usaa.com"], "USAA Rewards points total"),
  },
  {
    id: "fidelity-rewards",
    kind: "credit_card",
    displayName: "Fidelity Rewards",
    pointsCurrency: "Fidelity Rewards cash back",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: REVIEWED,
    region: "US",
    aliases: ["Fidelity cash back"],
    agentSkill: bankSeed("https://www.fidelity.com/", ["fidelity.com"], "Fidelity Rewards cash-back balance"),
  },
  {
    id: "rbc-avion",
    kind: "credit_card",
    displayName: "RBC Avion Rewards",
    pointsCurrency: "Avion points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: REVIEWED,
    region: "CA",
    aliases: ["RBC Rewards"],
    agentSkill: bankSeed("https://www.rbcroyalbank.com/", ["rbcroyalbank.com"], "Avion Rewards points total"),
  },
  {
    id: "td-rewards",
    kind: "credit_card",
    displayName: "TD Rewards",
    pointsCurrency: "TD Rewards points",
    estimatedCentsPerPoint: 0.7,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "CA",
    aliases: ["TD Points"],
    agentSkill: bankSeed("https://www.td.com/", ["td.com"], "TD Rewards points total"),
  },
  {
    id: "cibc-aventura",
    kind: "credit_card",
    displayName: "CIBC Aventura",
    pointsCurrency: "Aventura points",
    estimatedCentsPerPoint: 0.7,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "CA",
    aliases: ["CIBC Rewards"],
    agentSkill: bankSeed("https://www.cibc.com/", ["cibc.com"], "Aventura points total"),
  },
  {
    id: "bmo-rewards",
    kind: "credit_card",
    displayName: "BMO Rewards",
    pointsCurrency: "BMO Rewards points",
    estimatedCentsPerPoint: 0.7,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "CA",
    agentSkill: bankSeed("https://www.bmo.com/", ["bmo.com"], "BMO Rewards points total"),
  },
  {
    id: "amex-canada-membership-rewards",
    kind: "credit_card",
    displayName: "Amex Membership Rewards (Canada)",
    pointsCurrency: "Membership Rewards points (Canada)",
    estimatedCentsPerPoint: 1.1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "CA",
    aliases: ["Amex Canada MR"],
    agentSkill: bankSeed("https://www.americanexpress.com/ca/", ["americanexpress.com", "americanexpress.ca"], "Membership Rewards points total (Canada program; separate from US balance)"),
  },
  {
    id: "amex-uk-membership-rewards",
    kind: "credit_card",
    displayName: "Amex Membership Rewards (UK)",
    pointsCurrency: "Membership Rewards points (UK)",
    estimatedCentsPerPoint: 1.2,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "GB",
    aliases: ["Amex UK MR"],
    agentSkill: bankSeed("https://www.americanexpress.com/uk/", ["americanexpress.com"], "Membership Rewards points total (UK program; separate from US balance)"),
  },
  {
    id: "amex-singapore-membership-rewards",
    kind: "credit_card",
    displayName: "Amex Membership Rewards (Singapore)",
    pointsCurrency: "Membership Rewards points (Singapore)",
    estimatedCentsPerPoint: 0.6,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "SG",
    aliases: ["Amex SG MR"],
    agentSkill: bankSeed("https://www.americanexpress.com/sg/", ["americanexpress.com"], "Membership Rewards points total (Singapore program)"),
  },
  {
    id: "amex-australia-membership-rewards",
    kind: "credit_card",
    displayName: "Amex Membership Rewards (Australia)",
    pointsCurrency: "Membership Rewards points (Australia)",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "AU",
    aliases: ["Amex AU MR"],
    agentSkill: bankSeed("https://www.americanexpress.com/au/", ["americanexpress.com"], "Membership Rewards points total (Australia program)"),
  },
  {
    id: "dbs-points",
    kind: "credit_card",
    displayName: "DBS Points",
    pointsCurrency: "DBS Points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "SG",
    aliases: ["DBS Rewards"],
    agentSkill: bankSeed("https://www.dbs.com.sg/", ["dbs.com.sg", "dbs.com"], "DBS Points total"),
  },
  {
    id: "uob-uni-dollars",
    kind: "credit_card",
    displayName: "UOB UNI$",
    pointsCurrency: "UNI$",
    estimatedCentsPerPoint: 0.4,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "SG",
    aliases: ["UNI$", "UOB Rewards"],
    agentSkill: bankSeed("https://www.uob.com.sg/", ["uob.com.sg"], "UNI$ balance"),
  },
  {
    id: "ocbc-dollars",
    kind: "credit_card",
    displayName: "OCBC$",
    pointsCurrency: "OCBC$",
    estimatedCentsPerPoint: 0.7,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "SG",
    aliases: ["OCBC Rewards"],
    agentSkill: bankSeed("https://www.ocbc.com/", ["ocbc.com"], "OCBC$ balance"),
  },
  {
    id: "westpac-altitude-rewards",
    kind: "credit_card",
    displayName: "Westpac Altitude Rewards",
    pointsCurrency: "Altitude points",
    estimatedCentsPerPoint: 0.4,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "AU",
    aliases: ["Westpac Rewards"],
    agentSkill: bankSeed("https://www.westpac.com.au/", ["westpac.com.au"], "Altitude Rewards points total"),
  },
  {
    id: "anz-rewards",
    kind: "credit_card",
    displayName: "ANZ Rewards",
    pointsCurrency: "ANZ Reward Points",
    estimatedCentsPerPoint: 0.4,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "AU",
    agentSkill: bankSeed("https://www.anz.com.au/", ["anz.com.au"], "ANZ Rewards points total"),
  },
  {
    id: "commbank-awards",
    kind: "credit_card",
    displayName: "CommBank Awards",
    pointsCurrency: "Awards points",
    estimatedCentsPerPoint: 0.4,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "AU",
    aliases: ["CommBank Awards"],
    agentSkill: bankSeed("https://www.commbank.com.au/", ["commbank.com.au"], "Awards points total"),
  },
  {
    id: "nab-rewards",
    kind: "credit_card",
    displayName: "NAB Rewards",
    pointsCurrency: "NAB Rewards points",
    estimatedCentsPerPoint: 0.4,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "AU",
    agentSkill: bankSeed("https://www.nab.com.au/", ["nab.com.au"], "NAB Rewards points total"),
  },
] as const satisfies readonly ProviderDefinitionShape[];
