import type { ProviderDefinitionShape } from "./types";

const REVIEWED = "2026-10-01";

/**
 * Dining / food-delivery / coffee loyalty. Values are conservative editorial
 * estimates of the effective cents per point at typical redemption (usually a
 * free menu item); they vary with the item chosen and change often.
 */
export const DINING_PROVIDERS = [
  {
    id: "starbucks-rewards",
    kind: "dining",
    displayName: "Starbucks Rewards",
    pointsCurrency: "Stars",
    estimatedCentsPerPoint: 2,
    inactivityExpiryMonths: 6,
    confidence: "medium",
    lastReviewed: REVIEWED,
    aliases: ["Starbucks", "Stars"],
    region: "US",
    agentSkill: {
      startUrl: "https://www.starbucks.com/account/rewards",
      allowedHosts: ["starbucks.com"],
      hint: "Starbucks Stars balance on the Rewards page",
      notes: ["Start URL path unverified; Stars expire 6 months after earning."],
    },
  },
  {
    id: "chipotle-rewards",
    kind: "dining",
    displayName: "Chipotle Rewards",
    pointsCurrency: "Chipotle points",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: 3,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "US",
    agentSkill: {
      startUrl: "https://www.chipotle.com/rewards",
      allowedHosts: ["chipotle.com"],
      hint: "Chipotle Rewards points balance",
      notes: ["Start URL path unverified; points expire after about 3 months without activity."],
    },
  },
  {
    id: "dunkin-rewards",
    kind: "dining",
    displayName: "Dunkin' Rewards",
    pointsCurrency: "Dunkin' points",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: 12,
    confidence: "low",
    lastReviewed: REVIEWED,
    aliases: ["Dunkin Donuts"],
    region: "US",
  },
  {
    id: "mcdonalds-rewards",
    kind: "dining",
    displayName: "McDonald's Rewards",
    pointsCurrency: "MyMcDonald's Rewards points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    aliases: ["MyMcDonald's Rewards"],
    region: "US",
  },
  {
    id: "chick-fil-a-one",
    kind: "dining",
    displayName: "Chick-fil-A One",
    pointsCurrency: "Chick-fil-A One points",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    aliases: ["Chick-fil-A Rewards"],
    region: "US",
  },
  {
    id: "panera-rewards",
    kind: "dining",
    displayName: "Panera Rewards",
    pointsCurrency: "Panera points",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    aliases: ["Panera Bread", "MyPanera"],
    region: "US",
  },
  {
    id: "dominos-piece-of-the-pie",
    kind: "dining",
    displayName: "Domino's Piece of the Pie Rewards",
    pointsCurrency: "Domino's points",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: 6,
    confidence: "low",
    lastReviewed: REVIEWED,
    aliases: ["Domino's Rewards", "Piece of the Pie"],
    region: "US",
  },
  {
    id: "taco-bell-rewards",
    kind: "dining",
    displayName: "Taco Bell Rewards",
    pointsCurrency: "Taco Bell points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "US",
  },
  {
    id: "wendys-rewards",
    kind: "dining",
    displayName: "Wendy's Rewards",
    pointsCurrency: "Wendy's points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "US",
  },
  {
    id: "burger-king-royal-perks",
    kind: "dining",
    displayName: "Burger King Royal Perks",
    pointsCurrency: "Crowns",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    aliases: ["Royal Perks", "Crowns"],
    region: "US",
  },
  {
    id: "shake-shack-rewards",
    kind: "dining",
    displayName: "Shake Shack Rewards",
    pointsCurrency: "Shack Rewards points",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    aliases: ["Shack Rewards"],
    region: "US",
  },
  {
    id: "sweetgreen-rewards",
    kind: "dining",
    displayName: "Sweetgreen Rewards",
    pointsCurrency: "Sweetgreen points",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "US",
  },
  {
    id: "opentable-dining-points",
    kind: "dining",
    displayName: "OpenTable Dining Points",
    pointsCurrency: "Dining Points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: 12,
    confidence: "low",
    lastReviewed: REVIEWED,
    aliases: ["OpenTable"],
    agentSkill: {
      startUrl: "https://www.opentable.com/my/profile",
      allowedHosts: ["opentable.com"],
      hint: "OpenTable Dining Points balance on the profile page",
      notes: ["Start URL path unverified. 100 points redeem for a $5 dining cheque."],
    },
  },
  {
    id: "grubhub-perks",
    kind: "dining",
    displayName: "Grubhub Perks",
    pointsCurrency: "Perks points",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "US",
  },
  {
    id: "panda-express-rewards",
    kind: "dining",
    displayName: "Panda Rewards",
    pointsCurrency: "Panda points",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    aliases: ["Panda Express"],
    region: "US",
  },
  {
    id: "pizza-hut-hut-rewards",
    kind: "dining",
    displayName: "Pizza Hut Hut Rewards",
    pointsCurrency: "Hut Rewards points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "US",
  },
  {
    id: "papa-johns-papa-rewards",
    kind: "dining",
    displayName: "Papa Johns Papa Rewards",
    pointsCurrency: "Papa Points",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    region: "US",
  },
  {
    id: "tims-rewards",
    kind: "dining",
    displayName: "Tims Rewards",
    pointsCurrency: "Tims Rewards points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    aliases: ["Tim Hortons"],
    region: "CA",
  },
  {
    id: "costa-club",
    kind: "dining",
    displayName: "Costa Club",
    pointsCurrency: "Costa beans",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    aliases: ["Costa Coffee"],
    region: "GB",
  },
  {
    id: "pret-club-pret",
    kind: "dining",
    displayName: "Pret Club Pret",
    pointsCurrency: "Club Pret stars",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: REVIEWED,
    aliases: ["Pret A Manger"],
    region: "GB",
  },
] as const satisfies readonly ProviderDefinitionShape[];
