import type { ProviderDefinition } from "./types";

export const HOTEL_PROVIDERS: readonly ProviderDefinition[] = [
  {
    id: "marriott",
    kind: "hotel",
    displayName: "Marriott Bonvoy",
    pointsCurrency: "Bonvoy points",
    estimatedCentsPerPoint: 0.7,
    inactivityExpiryMonths: 24,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://www.marriott.com/loyalty/myAccount/default.mi",
      allowedHosts: ["marriott.com"],
      hint: "Bonvoy points balance on My Account",
    },
  },
  {
    id: "hilton",
    kind: "hotel",
    displayName: "Hilton Honors",
    pointsCurrency: "Honors points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://www.hilton.com/en/hilton-honors/guest/my-account/",
      allowedHosts: ["hilton.com"],
      hint: "Hilton Honors points on My Account",
    },
  },
  {
    id: "hyatt",
    kind: "hotel",
    displayName: "World of Hyatt",
    pointsCurrency: "World of Hyatt points",
    estimatedCentsPerPoint: 1.7,
    inactivityExpiryMonths: 24,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://www.hyatt.com/profile/en-US/account-overview",
      allowedHosts: ["hyatt.com"],
      hint: "World of Hyatt points on the account overview",
    },
  },
  {
    id: "ihg-one-rewards",
    kind: "hotel",
    displayName: "IHG One Rewards",
    pointsCurrency: "IHG points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: 12,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["IHG", "Priority Club", "Kimpton", "InterContinental"],
    agentSkill: {
      startUrl: "https://www.ihg.com/rewardsclub/us/en/account-mgmt/home",
      allowedHosts: ["ihg.com"],
      hint: "IHG One Rewards points balance on the account page",
    },
  },
  {
    id: "wyndham-rewards",
    kind: "hotel",
    displayName: "Wyndham Rewards",
    pointsCurrency: "Wyndham Rewards points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 18,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Wyndham"],
    agentSkill: {
      startUrl: "https://www.wyndhamhotels.com/wyndham-rewards/account",
      allowedHosts: ["wyndhamhotels.com"],
      hint: "Wyndham Rewards points on the account page",
    },
  },
  {
    id: "choice-privileges",
    kind: "hotel",
    displayName: "Choice Privileges",
    pointsCurrency: "Choice Privileges points",
    estimatedCentsPerPoint: 0.6,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Choice Hotels"],
    agentSkill: {
      startUrl: "https://www.choicehotels.com/choice-privileges/account",
      allowedHosts: ["choicehotels.com"],
      hint: "Choice Privileges points on the account page",
    },
  },
  {
    id: "best-western-rewards",
    kind: "hotel",
    displayName: "Best Western Rewards",
    pointsCurrency: "BWR points",
    estimatedCentsPerPoint: 0.6,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["BWR"],
    agentSkill: {
      startUrl: "https://www.bestwestern.com/en_US/best-western-rewards.html",
      allowedHosts: ["bestwestern.com"],
      hint: "Best Western Rewards points in the account header",
    },
  },
  {
    id: "radisson-rewards",
    kind: "hotel",
    displayName: "Radisson Rewards",
    pointsCurrency: "Radisson Rewards points",
    estimatedCentsPerPoint: 0.4,
    inactivityExpiryMonths: 24,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Radisson Hotels", "Club Carlson"],
  },
  {
    id: "accor-all",
    kind: "hotel",
    displayName: "Accor ALL",
    pointsCurrency: "ALL reward points",
    estimatedCentsPerPoint: 2.0,
    inactivityExpiryMonths: 12,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Accor Live Limitless", "Fairmont", "Sofitel", "Raffles", "Novotel"],
    agentSkill: {
      startUrl: "https://all.accor.com/account/index.en.shtml",
      allowedHosts: ["accor.com"],
      hint: "ALL reward points on the account page",
      notes: ["Value is a conservative blended estimate; points convert to EUR at a fixed ratio."],
    },
  },
  {
    id: "sonesta-travel-pass",
    kind: "hotel",
    displayName: "Sonesta Travel Pass",
    pointsCurrency: "Sonesta points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Sonesta"],
    region: "US",
  },
  {
    id: "omni-select-guest",
    kind: "hotel",
    displayName: "Omni Select Guest",
    pointsCurrency: "Select Guest points",
    estimatedCentsPerPoint: 0.8,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Omni Hotels"],
    region: "US",
  },
  {
    id: "loews-rewards",
    kind: "hotel",
    displayName: "Loews Rewards",
    pointsCurrency: "Loews points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Loews Hotels"],
    region: "US",
  },
  {
    id: "shangri-la-circle",
    kind: "hotel",
    displayName: "Shangri-La Circle",
    pointsCurrency: "Shangri-La Circle points",
    estimatedCentsPerPoint: 0.6,
    inactivityExpiryMonths: 24,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Shangri-La"],
  },
  {
    id: "langham-rewards",
    kind: "hotel",
    displayName: "Langham Rewards",
    pointsCurrency: "Langham Rewards points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Langham Hospitality"],
  },
  {
    id: "ascott-star-rewards",
    kind: "hotel",
    displayName: "Ascott Star Rewards",
    pointsCurrency: "Star Rewards points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: 24,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Ascott"],
  },
  {
    id: "melia-rewards",
    kind: "hotel",
    displayName: "Melia Rewards",
    pointsCurrency: "Melia Rewards points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: 24,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Meli\u00e1", "Melia Hotels"],
    region: "ES",
  },
  {
    id: "minor-discovery",
    kind: "hotel",
    displayName: "Minor DISCOVERY",
    pointsCurrency: "DISCOVERY points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: 24,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["NH Hotels", "NH Discovery", "Anantara"],
  },
  {
    id: "preferred-hotels-i-prefer",
    kind: "hotel",
    displayName: "I Prefer Hotel Rewards",
    pointsCurrency: "I Prefer points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 36,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Preferred Hotels", "I Prefer"],
  },
  {
    id: "leading-hotels-leaders-club",
    kind: "hotel",
    displayName: "Leaders Club",
    pointsCurrency: "Leaders Club points",
    estimatedCentsPerPoint: 0.3,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Leading Hotels of the World", "LHW"],
  },
  {
    id: "gha-discovery",
    kind: "hotel",
    displayName: "GHA DISCOVERY",
    pointsCurrency: "DISCOVERY Dollars",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 36,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Global Hotel Alliance", "GHA"],
  },
  {
    id: "slh-invited",
    kind: "hotel",
    displayName: "SLH Invited",
    pointsCurrency: "SLH points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: 24,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Small Luxury Hotels", "Invited"],
  },
  {
    id: "expedia-one-key",
    kind: "hotel",
    displayName: "Expedia One Key",
    pointsCurrency: "OneKeyCash",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: 18,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["One Key", "Hotels.com Rewards"],
  },
  {
    id: "booking-genius",
    kind: "hotel",
    displayName: "Booking.com Genius",
    pointsCurrency: "Genius credits",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Genius", "Booking.com"],
  },
];
