import type { ProviderDefinition } from "./types";

export const OTHER_PROVIDERS: readonly ProviderDefinition[] = [
  {
    id: "amtrak",
    kind: "rail",
    displayName: "Amtrak Guest Rewards",
    pointsCurrency: "Guest Rewards points",
    estimatedCentsPerPoint: 2.5,
    inactivityExpiryMonths: 36,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://www.amtrak.com/guestrewards/account-overview",
      allowedHosts: ["amtrak.com"],
      hint: "Amtrak Guest Rewards points on the account overview",
    },
  },
  {
    id: "rakuten",
    kind: "shopping",
    displayName: "Rakuten Rewards",
    pointsCurrency: "Rakuten points",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    agentSkill: {
      startUrl: "https://www.rakuten.com/account/summary",
      allowedHosts: ["rakuten.com"],
      hint: "Rakuten Cash Back balance (dollars; report as whole cents)",
      notes: ["Balance is in dollars: submit whole cents (e.g. $12.34 -> 1234)."],
    },
  },
  {
    id: "via-rail-preferred",
    kind: "rail",
    displayName: 'VIA Preferred',
    pointsCurrency: 'VIA Preferred points',
    estimatedCentsPerPoint: 1.5,
    inactivityExpiryMonths: 24,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["VIA Rail"],
    region: "CA",
  },
  {
    id: "club-eurostar",
    kind: "rail",
    displayName: 'Club Eurostar (Eurostar Loyalty)',
    pointsCurrency: 'Club Eurostar points',
    estimatedCentsPerPoint: 1.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Eurostar"],
    region: "GB",
  },
  {
    id: "db-bahnbonus",
    kind: "rail",
    displayName: 'Deutsche Bahn BahnBonus',
    pointsCurrency: 'BahnBonus points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: 36,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["BahnBonus", "Deutsche Bahn"],
    region: "DE",
  },
  {
    id: "sncf-grand-voyageur",
    kind: "rail",
    displayName: 'SNCF Grand Voyageur',
    pointsCurrency: 'Grand Voyageur points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["SNCF Connect", "Grand Voyageur Le Club"],
    region: "FR",
  },
  {
    id: "trenitalia-cartafreccia",
    kind: "rail",
    displayName: 'Trenitalia CartaFRECCIA',
    pointsCurrency: 'CartaFRECCIA points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["CartaFreccia", "Trenitalia"],
    region: "IT",
  },
  {
    id: "renfe-mas",
    kind: "rail",
    displayName: 'Renfe +Renfe',
    pointsCurrency: '+Renfe points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Renfe", "Mas Renfe"],
    region: "ES",
  },
  {
    id: "brightline-rewards",
    kind: "rail",
    displayName: 'Brightline Rewards',
    pointsCurrency: 'Brightline points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Brightline"],
    region: "US",
  },
  {
    id: "capital-one-shopping",
    kind: "shopping",
    displayName: 'Capital One Shopping',
    pointsCurrency: 'Capital One Shopping Credits',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    region: "US",
    agentSkill: {
      startUrl: "https://capitalone.com/shopping",
      allowedHosts: ["capitalone.com"],
      hint: 'Capital One Shopping credits balance',
      notes: ['Credits are roughly 1 cent each; start URL unverified.'],
    },
  },
  {
    id: "ibotta",
    kind: "shopping",
    displayName: 'Ibotta',
    pointsCurrency: 'Ibotta cash',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    region: "US",
    agentSkill: {
      startUrl: "https://ibotta.com/",
      allowedHosts: ["ibotta.com"],
      hint: 'Ibotta cash balance',
      notes: ['Cash balance in dollars; submit whole cents (1 unit = 1 cent). Start URL is the site root, unverified account path.'],
    },
  },
  {
    id: "fetch-rewards",
    kind: "shopping",
    displayName: 'Fetch Rewards',
    pointsCurrency: 'Fetch points',
    estimatedCentsPerPoint: 0.1,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Fetch"],
    region: "US",
  },
  {
    id: "shopkick",
    kind: "shopping",
    displayName: 'Shopkick',
    pointsCurrency: 'Kicks',
    estimatedCentsPerPoint: 0.03,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Kicks"],
    region: "US",
  },
  {
    id: "swagbucks",
    kind: "shopping",
    displayName: 'Swagbucks',
    pointsCurrency: 'SB',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["SB"],
  },
  {
    id: "target-circle",
    kind: "shopping",
    displayName: 'Target Circle',
    pointsCurrency: 'Target Circle earnings',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Target Circle Rewards"],
    region: "US",
  },
  {
    id: "best-buy-my-best-buy",
    kind: "shopping",
    displayName: 'My Best Buy',
    pointsCurrency: 'My Best Buy points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: 12,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Best Buy Rewards"],
    region: "US",
  },
  {
    id: "kroger-fuel-points",
    kind: "shopping",
    displayName: 'Kroger Fuel Points',
    pointsCurrency: 'Fuel points (1 point = 1 cent off per gallon)',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: 1,
    confidence: "medium",
    lastReviewed: "2026-10-01",
    aliases: ["Kroger Plus Card"],
    region: "US",
  },
  {
    id: "shell-fuel-rewards",
    kind: "shopping",
    displayName: 'Shell Fuel Rewards',
    pointsCurrency: 'Fuel Rewards savings (cents per gallon)',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Fuel Rewards"],
    region: "US",
  },
  {
    id: "bp-me-rewards",
    kind: "shopping",
    displayName: 'BP bp me Rewards',
    pointsCurrency: 'bp me rewards points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["bp me"],
  },
  {
    id: "exxon-mobil-rewards-plus",
    kind: "shopping",
    displayName: 'Exxon Mobil Rewards+',
    pointsCurrency: 'Rewards+ points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Exxon Rewards"],
    region: "US",
  },
  {
    id: "chevron-texaco-rewards",
    kind: "shopping",
    displayName: 'Chevron Texaco Rewards',
    pointsCurrency: 'Chevron Texaco Rewards points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Chevron"],
    region: "US",
  },
  {
    id: "sephora-beauty-insider",
    kind: "shopping",
    displayName: 'Sephora Beauty Insider',
    pointsCurrency: 'Beauty Insider points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: 24,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Sephora"],
    region: "US",
  },
  {
    id: "ulta-ultamate-rewards",
    kind: "shopping",
    displayName: 'Ulta Beauty Ultamate Rewards',
    pointsCurrency: 'Ultamate Rewards points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Ulta"],
    region: "US",
  },
  {
    id: "nordstrom-nordy-club",
    kind: "shopping",
    displayName: 'Nordstrom Nordy Club',
    pointsCurrency: 'Nordy Club points',
    estimatedCentsPerPoint: 2,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Nordstrom Rewards"],
    region: "US",
  },
  {
    id: "macys-star-rewards",
    kind: "shopping",
    displayName: "Macy's Star Rewards",
    pointsCurrency: 'Star Rewards points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Macy's"],
    region: "US",
  },
  {
    id: "kohls-rewards",
    kind: "shopping",
    displayName: "Kohl's Rewards",
    pointsCurrency: "Kohl's Rewards points",
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Kohl's"],
    region: "US",
  },
  {
    id: "staples-rewards",
    kind: "shopping",
    displayName: 'Staples Rewards',
    pointsCurrency: 'Staples Rewards (dollars)',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Staples"],
    region: "US",
  },
  {
    id: "office-depot-rewards",
    kind: "shopping",
    displayName: 'Office Depot Rewards',
    pointsCurrency: 'Office Depot Rewards (dollars)',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["OfficeMax Rewards"],
    region: "US",
  },
  {
    id: "nectar",
    kind: "shopping",
    displayName: 'Nectar',
    pointsCurrency: 'Nectar points',
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Sainsbury's Nectar"],
    region: "GB",
  },
  {
    id: "tesco-clubcard",
    kind: "shopping",
    displayName: 'Tesco Clubcard',
    pointsCurrency: 'Clubcard points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: 36,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Clubcard"],
    region: "GB",
  },
  {
    id: "air-miles-canada",
    kind: "shopping",
    displayName: 'Air Miles (Canada)',
    pointsCurrency: 'Air Miles reward miles',
    estimatedCentsPerPoint: 10,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["AIR MILES"],
    region: "CA",
  },
  {
    id: "scene-plus",
    kind: "shopping",
    displayName: 'Scene+',
    pointsCurrency: 'Scene+ points',
    estimatedCentsPerPoint: 1,
    inactivityExpiryMonths: 24,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Scene Plus", "Scotiabank Scene+"],
    region: "CA",
  },
  {
    id: "pc-optimum",
    kind: "shopping",
    displayName: 'PC Optimum',
    pointsCurrency: 'PC Optimum points',
    estimatedCentsPerPoint: 0.1,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["President's Choice Optimum"],
    region: "CA",
  },
  {
    id: "flybuys",
    kind: "shopping",
    displayName: 'Flybuys',
    pointsCurrency: 'Flybuys points',
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Coles Flybuys"],
    region: "AU",
  },
  {
    id: "everyday-rewards",
    kind: "shopping",
    displayName: 'Woolworths Everyday Rewards',
    pointsCurrency: 'Everyday Rewards points',
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Woolworths Rewards"],
    region: "AU",
  },
  {
    id: "payback-de",
    kind: "shopping",
    displayName: 'PAYBACK (Germany)',
    pointsCurrency: 'PAYBACK Punkte',
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: 36,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Payback", "Payback Punkte"],
    region: "DE",
  },
];
