import type { ProviderDefinitionShape } from "./types";

export const TRAVEL_PROVIDERS = [
  {
    id: "hertz-gold-plus-rewards",
    kind: "car_rental",
    displayName: "Hertz Gold Plus Rewards",
    pointsCurrency: "Gold Plus Rewards points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Hertz", "Hertz Gold"],
    agentSkill: {
      startUrl: "https://www.hertz.com/rentacar/member/account",
      allowedHosts: ["hertz.com"],
      hint: "Gold Plus Rewards points on the account page",
    },
  },
  {
    id: "avis-preferred",
    kind: "car_rental",
    displayName: "Avis Preferred",
    pointsCurrency: "Avis Preferred points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Avis"],
    agentSkill: {
      startUrl: "https://www.avis.com/en/profile",
      allowedHosts: ["avis.com"],
      hint: "Avis Preferred points on the profile page",
    },
  },
  {
    id: "national-emerald-club",
    kind: "car_rental",
    displayName: "National Emerald Club",
    pointsCurrency: "Emerald Club credits",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Emerald Club", "National"],
    agentSkill: {
      startUrl: "https://www.nationalcar.com/en/profile",
      allowedHosts: ["nationalcar.com"],
      hint: "Emerald Club credits on the profile page",
      notes: ["Rewards are rental credits; submit the credit count shown."],
    },
  },
  {
    id: "enterprise-plus",
    kind: "car_rental",
    displayName: "Enterprise Plus",
    pointsCurrency: "Enterprise Plus points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Enterprise"],
    agentSkill: {
      startUrl: "https://www.enterprise.com/en/account.html",
      allowedHosts: ["enterprise.com"],
      hint: "Enterprise Plus points on the account page",
    },
  },
  {
    id: "sixt-advantage-circle",
    kind: "car_rental",
    displayName: "Sixt Advantage Circle",
    pointsCurrency: "Advantage Circle points",
    estimatedCentsPerPoint: 0.5,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Sixt"],
  },
  {
    id: "budget-fastbreak",
    kind: "car_rental",
    displayName: "Budget Fastbreak",
    pointsCurrency: "Fastbreak points",
    estimatedCentsPerPoint: 0.4,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Budget"],
  },
  {
    id: "alamo-insiders",
    kind: "car_rental",
    displayName: "Alamo Insiders",
    pointsCurrency: "Alamo Insiders points",
    estimatedCentsPerPoint: 0.4,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Alamo"],
  },
  {
    id: "thrifty-blue-chip",
    kind: "car_rental",
    displayName: "Thrifty Blue Chip",
    pointsCurrency: "Blue Chip points",
    estimatedCentsPerPoint: 0.4,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Thrifty"],
  },
  {
    id: "royal-caribbean-crown-anchor",
    kind: "cruise",
    displayName: "Crown & Anchor Society",
    pointsCurrency: "Cruise points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Royal Caribbean"],
  },
  {
    id: "carnival-vifp-club",
    kind: "cruise",
    displayName: "Carnival VIFP Club",
    pointsCurrency: "VIFP points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Carnival", "VIFP"],
  },
  {
    id: "norwegian-latitudes-rewards",
    kind: "cruise",
    displayName: "Norwegian Latitudes Rewards",
    pointsCurrency: "Latitudes points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["NCL", "Norwegian Cruise Line"],
  },
  {
    id: "princess-captains-circle",
    kind: "cruise",
    displayName: "Princess Captain's Circle",
    pointsCurrency: "Captain's Circle points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Princess Cruises"],
  },
  {
    id: "celebrity-captains-club",
    kind: "cruise",
    displayName: "Celebrity Captain's Club",
    pointsCurrency: "Captain's Club points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Celebrity Cruises"],
  },
  {
    id: "holland-america-mariner-society",
    kind: "cruise",
    displayName: "Holland America Mariner Society",
    pointsCurrency: "Mariner Society points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Holland America Line"],
  },
  {
    id: "msc-voyagers-club",
    kind: "cruise",
    displayName: "MSC Voyagers Club",
    pointsCurrency: "Voyagers Club points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["MSC Cruises"],
  },
  {
    id: "cunard-world-club",
    kind: "cruise",
    displayName: "Cunard World Club",
    pointsCurrency: "World Club points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Cunard"],
    region: "GB",
  },
  {
    id: "uber-rewards",
    kind: "rideshare",
    displayName: "Uber Rewards",
    pointsCurrency: "Uber Rewards points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Uber", "Uber One"],
    agentSkill: {
      startUrl: "https://riders.uber.com/profile",
      allowedHosts: ["uber.com"],
      hint: "Uber Rewards points on the rider profile",
      notes: ["Uber also shows dollar-denominated Uber Cash and Uber One credits; submit the Uber Rewards points count, not the dollar balance."],
    },
  },
  {
    id: "lyft-rewards",
    kind: "rideshare",
    displayName: "Lyft Rewards",
    pointsCurrency: "Lyft Rewards points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Lyft", "Lyft Pink"],
    agentSkill: {
      startUrl: "https://www.lyft.com/rewards",
      allowedHosts: ["lyft.com"],
      hint: "Lyft points balance on the rewards page",
      notes: ["Lyft may show ride credits in dollars rather than points; submit points when shown, otherwise the dollar credit."],
    },
  },
  {
    id: "bolt-rewards",
    kind: "rideshare",
    displayName: "Bolt Rewards",
    pointsCurrency: "Bolt points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Bolt"],
  },
  {
    id: "grab-rewards",
    kind: "rideshare",
    displayName: "GrabRewards",
    pointsCurrency: "GrabRewards points",
    estimatedCentsPerPoint: 0.1,
    inactivityExpiryMonths: 12,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Grab"],
    region: "SG",
  },
  {
    id: "didi-points",
    kind: "rideshare",
    displayName: "DiDi Rewards",
    pointsCurrency: "DiDi points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["DiDi"],
  },
  {
    id: "gett-rewards",
    kind: "rideshare",
    displayName: "Gett Rewards",
    pointsCurrency: "Gett points",
    estimatedCentsPerPoint: 1.0,
    inactivityExpiryMonths: null,
    confidence: "low",
    lastReviewed: "2026-10-01",
    aliases: ["Gett"],
  },
] as const satisfies readonly ProviderDefinitionShape[];
